services:
  node1:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./node1_storage:/app/storage
    networks:
      - p2pnet

  node2:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - ./node2_storage:/app/storage
    networks:
      - p2pnet

networks:
  p2pnet:
